language: go

go:
  - '1.5'
  - '1.6'
  - '1.7'
  - 'tip'

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go build
  - ! gofmt -d path/to/file.go 2>&1 | read
