language: go
go:
  - '1.7'
  - 'tip'

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/kardianos/govendor

script:
  - govendor sync
  - govendor install
  - goveralls -service=travis-ci
